spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/shoppingmall"
    username: sa
    password:
  profiles:
    include: security
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      repositories:
        enabled: false

server:
  servlet:
    session:
      cookie:
        same-site: none
        http-only: false
        max-age: 30m
        secure: on
