spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/shoppingmall"
    username: sa
    password:
  profiles:
    include: security
  jpa:
    hibernate:
      ddl-auto: create

